chore: Update DockerHub workflow to support new platform configurations

diff --git a/.github/workflows/build-dockerhub.yml b/.github/workflows/build-dockerhub.yml
--- a/.github/workflows/build-dockerhub.yml
+++ b/.github/workflows/build-dockerhub.yml
@@ -17,7 +17,7 @@ jobs:
       matrix:
         config:
           - { platform: linux-amd64, dist: "debian", target: x86_64-unknown-linux-gnu }
-          # - { platform: linux-arm64-v8, dist: "debian", target: aarch64-unknown-linux-gnu }
+          - { platform: linux-arm64-v8, dist: "debian", target: aarch64-unknown-linux-gnu }
           # - { platform: linux-amd64, dist: alpine, target: x86_64-unknown-linux-musl }
           # - { platform: linux-arm64-v8, dist: alpine, target: aarch64-unknown-linux-musl }
     environment: PROD
@@ -73,8 +73,7 @@ jobs:
       matrix:
         include:
           - { dist: "debian", architecture: "linux/amd64,linux/arm64/v8" }
-          # - { platform: linux-x64-alpine, os: ubuntu-latest, architecture: linux/amd64 }
-          # - { platform: linux-arm64-alpine, os: ubuntu-latest, architecture: linux/arm64/v8 }
+          # - { dist: "alpine", architecture: "linux/amd64,linux/arm64/v8" }
 
     steps:
       - name: Checkout code
@@ -89,33 +88,33 @@ jobs:
       - name: List files
         run: ls -la build
 
-      - name: Ensure tagoio-relay exists
-        run: |
-          if [ ! -f build/tagoio-relay ]; then
-            echo "tagoio-relay not found in build folder"
-            exit 1
-          fi
+      # - name: Ensure tagoio-relay exists
+      #   run: |
+      #     if [ ! -f build/tagoio-relay ]; then
+      #       echo "tagoio-relay not found in build folder"
+      #       exit 1
+      #     fi
 
-      # - name: Set up QEMU
-      #   uses: docker/setup-qemu-action@v3
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
 
-      # - name: Set up Docker Buildx
-      #   uses: docker/setup-buildx-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-      # - name: Cache Docker layers
-      #   uses: actions/cache@v4
-      #   with:
-      #     path: /tmp/.buildx-cache
-      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-buildx-
+      - name: Cache Docker layers
+        uses: actions/cache@v4
+        with:
+          path: /tmp/.buildx-cache
+          key: ${{ runner.os }}-buildx-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-buildx-
 
-      # - name: Login to DockerHub
-      #   uses: docker/login-action@v3
-      #   with:
-      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
-      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Login to DockerHub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      #     # linux/arm64/v8,linux/amd64
-      # - name: Build and deploy images
-      #   run: bash dockerhub.sh ${{ matrix.architecture }} ${{ github.event.inputs.version || github.event.release.tag_name }}
+          # linux/arm64/v8,linux/amd64
+      - name: Build and deploy images
+        run: bash dockerhub.sh ${{ matrix.dist }} ${{ matrix.architecture }} ${{ github.event.inputs.version || github.event.release.tag_name }}
